# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'welcome_tour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for welcome_tour
pod 'iCarousel'
pod 'ImageSlideshow', '~> 1.9.0'
pod ‘GoogleMaps’

end
